# -*- coding: utf-8 -*-
"""VRSU-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1De_rnNscfrOh7luKjDbuNy8rfwJwRsmb
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

uploaded=files.upload()
image_path=list(uploaded.keys())[0]

img=cv2.imread(image_path)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

plt.figure(figsize=(3,3))
plt.imshow(gray,cmap="gray")
plt.axis("off")
plt.show()

orb=cv2.ORB_create(nfeatures=500)
kp_orb,des_orb=orb.detectAndCompute(gray,None)
orb_img=cv2.drawKeypoints(gray,kp_orb,None,flags=cv2.DRAW_MATCHES_FLAGS_DEFAULT)

plt.figure(figsize=(3,3))
plt.imshow(orb_img,cmap="gray")
plt.axis("off")
plt.show()

print("ORB Features:",len(kp_orb))
print("ORB Descriptor Shape:",des_orb.shape)

sift=cv2.SIFT_create()
kp_sift,des_sift=sift.detectAndCompute(gray,None)
sift_img=cv2.drawKeypoints(gray,kp_sift,None,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

plt.figure(figsize=(3,3))
plt.imshow(sift_img,cmap="gray")
plt.axis("off")
plt.show()

print("SIFT Features:",len(kp_sift))
print("SIFT Descriptor Shape:",des_sift.shape)

try:
    surf=cv2.xfeatures2d.SURF_create(400)
    kp_surf,des_surf=surf.detectAndCompute(gray,None)
    surf_img=cv2.drawKeypoints(gray,kp_surf,None,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

    plt.figure(figsize=(3,3))
    plt.imshow(surf_img,cmap="gray")
    plt.axis("off")
    plt.show()

    print("SURF Features:",len(kp_surf))
    print("SURF Descriptor Shape:",des_surf.shape)
except:
    print("SURF not supported")